name: Mutants

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mutants:
    uses: mozilla/actions/.github/workflows/mutants.yml@25cb84d060946c0ad6d2c3f79da479b16d180d71 # v1.1.0
